from telegram import Update
from telegram.ext import ContextTypes
from bot.config import OWNER_IDS

async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id
    is_owner = (user_id in OWNER_IDS)

    user_text = (
        "🤖 *Invite Link Management Bot*\n\n"
        "🔹 *User Commands*\n"
        "/start – Get your personal invite link\n"
        "/help – Show this message\n\n"
        "🔹 *How It Works*\n"
        "• Send /start to get your unique invite link\n"
        "• Click the link to join the group/channel\n"
        "• Your link is single-use and expires automatically\n\n"
        "📌 *Rules*\n"
        "• Never share your personal invite link\n"
        "• Expired links cannot be reused\n"
        "• Contact an admin if you have issues\n\n"
        "Created by @TeamJB_bot"
    )

    owner_text = (
        "\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "👑 *OWNER COMMANDS*\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
        
        "📌 *SYSTEM OVERVIEW*\n"
        "The bot has TWO independent invite link systems.\n"
        "Only ONE system works at a time. Switch between them with:\n"
        "`/activelinkmode on` – Use System 2 (Shared Links)\n"
        "`/activelinkmode off` – Use System 1 (Default Links)\n\n"
        
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🔹 *SYSTEM 1 – DEFAULT AUTO-LINKS*\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
        "📝 *What it does:*\n"
        "Each user gets a UNIQUE invite link when they send /start\n\n"
        "⚙️ *Setup:*\n"
        "1. `/setdefaultlink <chat_id> <expiry> <max_uses>`\n"
        "   Example: `/setdefaultlink -1001234567890 86400 1`\n\n"
        "   • `chat_id` – Group/channel ID (get from @get_id_bot)\n"
        "   • `expiry` – Link validity in seconds\n"
        "     3600 = 1 hour | 86400 = 1 day | 604800 = 7 days\n"
        "   • `max_uses` – How many times link can be used\n"
        "     1 = single-use | 10 = 10 uses | 0 = unlimited\n\n"
        "2. `/setdefaultlink list` – View all templates\n"
        "3. `/setdefaultlink remove <chat_id>` – Remove a template\n"
        "4. `/activelinkmode off` – Activate System 1\n\n"
        "✅ *Result:* Each user gets their own unique link\n\n"
        
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🔹 *SYSTEM 2 – SHARED LINKS*\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
        "📝 *What it does:*\n"
        "All users receive the SAME invite link when they send /start\n\n"
        "⚙️ *Setup:*\n"
        "1. `/create_link` – Create a custom link (interactive menu)\n"
        "   • Select group/channel\n"
        "   • Choose expiry time\n"
        "   • Choose max uses\n\n"
        "2. Copy the link ID (e.g., `+ABC123XYZ`)\n\n"
        "3. `/setactivelink +ABC123XYZ` – Set as active link\n"
        "   • Can set multiple: `/setactivelink +ABC +DEF`\n"
        "   • Clear all: `/setactivelink clear`\n\n"
        "4. `/activelinkmode on` – Activate System 2\n\n"
        "✅ *Result:* All users get the same link\n\n"
        
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🔹 *LINK MANAGEMENT*\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
        "`/create_link` – Create custom invite link (interactive)\n"
        "`/active_links` – View your active links\n"
        "`/listlinks` – View ALL links (owner only)\n"
        "`/revoke_link +ID` – Revoke a specific link\n"
        "`/revoke_all` – Revoke ALL active links\n"
        "`/setactivelink +ID` – Set active link(s) for System 2\n"
        "`/setactivelink clear` – Clear all active links\n"
        "`/activelinkmode on/off` – Switch between systems\n"
        "`/defaultlinkstatus` – Show current system status\n\n"
        
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🔹 *GROUP MANAGEMENT*\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
        "`/addgroup <group_id> <title>` – Register a group\n"
        "  Example: `/addgroup -1001234567890 My Group`\n\n"
        "`/addgroups <id1:title1> <id2:title2> ...` – Add multiple\n"
        "  Example: `/addgroups -100111:Group1 -100222:Group2`\n\n"
        "`/settings` – Interactive settings menu per group\n"
        "`/setlogchannel <group_id> <channel_id>` – Set log channel\n"
        "  Example: `/setlogchannel -100123 -100456`\n\n"
        "`/setwelcome <group_id> <message>` – Set welcome message\n"
        "  Use `{user}` for user name, `{link_creator}` for creator\n"
        "  Example: `/setwelcome -100123 Welcome {user}!`\n\n"
        "`/togglewelcome on/off` – Enable/disable welcome messages\n\n"
        
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🔹 *ADMIN MANAGEMENT*\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
        "`/admins` – View all admins with management menu\n"
        "`/addadmin <user_id> <role>` – Add a new admin\n"
        "  Roles: `admin`, `super_admin`, `owner`\n"
        "  Example: `/addadmin 123456789 super_admin`\n\n"
        
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🔹 *DATABASE & UTILITIES*\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
        "`/stats` – View bot statistics\n"
        "  • Total links created\n"
        "  • Active links\n"
        "  • Total joins\n"
        "  • Registered users\n\n"
        "`/backup` – Generate full JSON backup\n"
        "`/restore` – Restore from backup (send JSON file)\n"
        "`/dashboard` – Interactive admin panel with buttons\n"
        "`/help` – Show this message\n\n"
        
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "📊 *EXPIRY TIME REFERENCE*\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
        "• 3600     = 1 hour\n"
        "• 21600    = 6 hours\n"
        "• 43200    = 12 hours\n"
        "• 86400    = 24 hours (1 day)\n"
        "• 172800   = 48 hours (2 days)\n"
        "• 604800   = 7 days\n"
        "• 2592000  = 30 days\n\n"
        
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "⚠️ *IMPORTANT NOTES*\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
        "• Bot MUST be admin in groups/channels with:\n"
        "  ✅ Create Invite Links\n"
        "  ✅ Send Messages (for logs)\n"
        "  ✅ Approve Join Requests (for groups)\n\n"
        "• System 1 vs System 2:\n"
        "  🔹 System 1 = Unique links per user\n"
        "  🔹 System 2 = Same link for all users\n\n"
        "• Only ONE system works at a time\n"
        "• Switch with `/activelinkmode on/off`\n\n"
        "• All settings stored in MongoDB\n"
        "• Settings survive bot restarts\n\n"
        
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        "🔗 *NEED HELP?*\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
        "Contact @TeamJB_bot for support\n"
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    )

    if is_owner:
        await update.message.reply_text(user_text + owner_text, parse_mode="Markdown")
    else:
        await update.message.reply_text(user_text, parse_mode="Markdown")
